Add invert function
remeda/remeda pull request #236
Opened 2022-12-19 06:45 UTC by LandonSchropp

This adds the handy `invert` method, which swaps the keys and values in an object. This method is present in both Lodash and Ramda, and I needed it for my current project, so I thought I'd add it here as well.

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `mapping.md`

2022-12-25 18:58 UTC, TkDodo commented
entries in `index` and `mapping.md` are missing please

2023-01-06 23:23 UTC, LandonSchropp commented
I forgot to force-push the commit after I added them. 🙂

2023-01-15 04:56 UTC, texastoland commented
I think I accidentally wrote a more exact type for this that works with `as const` in sindresorhus/type-fest#543.

2023-01-15 10:08 UTC, TkDodo requested changes
thanks for this PR, please have a look at my comments

2023-01-15 10:08 UTC, TkDodo commented on src/invert.ts
> +export function invert<T>(): (object: Invertable) => Inverted;
please also add jsdocs for the `data-last` version and add the `@category`

2023-01-15 10:08 UTC, TkDodo commented on src/invert.ts
> + *    ); // => { d: "a", e: "b", f: "c" }
this is actually the `data-last` example, that would need to go on the other method please. Also, the code needs to work, and there is a missing comma here. This is why the build fails:

```
12:26:59 AM: SyntaxError: ',' expected. (5:6)
12:26:59 AM:   3 |    R.pipe(
12:26:59 AM:   4 |      { a: "d", b: "e", c: "f" }
12:26:59 AM: > 5 |      R.invert()
12:26:59 AM:     |      ^
12:26:59 AM:   6 |    ); // => { d: "a", e: "b", f: "c" }
```

2023-01-15 10:08 UTC, TkDodo commented on src/invert.ts
> +type Inverted = { [index: string]: string };
as @texastoland has pointed out, I think the types could be improved here to have a relation with each other. The generic `T` you've added to `invert` is actually unused ...

2023-05-22 13:02 UTC, TkDodo commented
closing due to staleness

2023-05-22 13:02 UTC, closed without merging

2023-05-24 19:16 UTC, LandonSchropp commented
@TkDodo Sorry for the staleness on this! I had a baby at the end of last year, and this completely slipped off my radar. I'll make the changes you suggested and push up a new branch today. 🙂

2023-05-24 21:59 UTC, texastoland commented
Happy to review too and congrats 👶🏼

2023-05-25 19:05 UTC, LandonSchropp commented
@TkDodo and @texastoland: I think I got the types refined a bit. I'll be honest, I wasn't quite following everything in the type that @texastoland posted. Here's what I wrote:

``` typescript
type Invertable =  Record<PropertyKey, PropertyKey> | PropertyKey[];
type Inverted<T extends Invertable> = Record<Extract<T[keyof T], PropertyKey>, T[keyof T]>

function _invert<T extends Invertable>(object: T): Inverted<T> {
  return Object.entries(object).reduce((accumulator, [key, value]) => {
    accumulator[value] = key;
    return accumulator;
  }, {} as Inverted<T>)
}
```

If that doesn't work, could you please walk me through where any issues might be? Thanks in advance!