fix(flatMap): should accept fn returning a readonly array
remeda/remeda pull request #401
Opened 2023-10-22 22:53 UTC by RedHatter

`flatMap` currently accepts a predicate of `(input: T) => K | Array<K>` however there's no reason the returned array needs to be mutable. This fails when trying to return a readonly array.

This PR updates the predicate type to `(input: T) => K | ReadonlyArray<K>`

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `mapping.md`

---

<details><summary>We use semantic PR titles to automate the release process!</summary>

https://conventionalcommits.org

PRs should be titled following using the format: `< TYPE >(< scope >)?: description`

### Available Types:

- `feat`: new functions!
- `fix`: changes to function implementations that fix a bug where a function produces the wrong _runtime_ results.
- `type`: type-only changes (params, overloading, return types, etc...)
- `perf`: changes to function implementations that improve a functions _runtime_ performance.
- `refactor`: changes to function implementations that are neither `fix` nor `perf`
- `test`: tests-only changes (transparent to users of the function).
- `docs`: changes to the documentation of a function **or the documentation site**.
- `build`, `ci`, `style`, `chore`, and `revert`: are only relevant for the internals of the library.

For scope put the name of the function you are working on (either new or
existing).

</details>

2023-10-23 06:14 UTC, eranhirsch requested changes
This looks great:
https://github.com/microsoft/TypeScript/blob/8af8f3c4d1e5cc6654916de9f42e9ba370513157/src/lib/es2019.array.d.ts#L19

Can you also fix the dataLast function signature? you only did the dataFirst one

2023-10-23 06:14 UTC, eranhirsch commented on src/flatMap.test.ts
> +    x => [x * 2, x * 3] as ReadonlyArray<number>
would be enough to just do as const here
```suggestion
    x => [x * 2, x * 3] as const
```

2023-10-23 07:38 UTC, RedHatter commented
Done

2023-10-23 07:40 UTC, eranhirsch approved these changes
Thanks!

2023-10-25 05:02 UTC, RedHatter commented
@eranhirsch Can we get this merged? Thanks!

2023-10-25 05:13 UTC, eranhirsch commented
Sorry, I don't usually do the merges. It will probably be merged and added to the next version by the end of this week

2023-10-25 05:30 UTC, merged

2023-10-25 05:33 UTC, TkDodo commented
:tada: This PR is included in version 1.28.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/remeda/v/1.28.0)
- [GitHub release](https://github.com/remeda/remeda/releases/tag/v1.28.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: