Feature/guards
remeda/remeda pull request #67
Opened 2020-05-12 08:38 UTC by digimuza

Added common utility typescript guards.

Tested with Array.filter method and simple condition

2020-08-25 14:35 UTC, maxfi commented
LGTM! :tada:

2020-09-04 17:44 UTC, lstkz requested changes
Thanks, looks good. Few issues:
- Autoformat code with prettier.
- Add guards to index.ts.
- Add JsDoc without it online documentation can't be automatically created.

2021-02-24 16:49 UTC, r01010010 commented
@digimuza Any updates on this? @lstkz this PR is almost one year old. 

We're very interested in this library in our team because is the only one we found 100% compatible with our typescript needs.

2021-02-24 17:07 UTC, digimuza commented
Hmm, I forgot about this merge request.  I needed to wait 4 months for any response. So I abandoned this library and created my own.
https://digimuza.github.io/ts-prime/#/home
I liked the idea of remeda but remeda just ties to be lodash. What I wanted is to have general use the utility library for typescript.

2021-06-14 07:49 UTC, lstkz commented
@TkDodo @r01010010 @digimuza 
We can merge this PR but request changes must be implemented first. Especially the js docs because we don't want to add non-documented functions.

2021-06-14 07:54 UTC, TkDodo commented
@lstkz I will try to take over this PR. If I cannot add commits, I will open a new one with the changes copied over. My goal would be to get it done this week if that's alright ...

2021-06-15 15:14 UTC, TkDodo commented
@lstkz I added jsdocs for the `isString` guard and wanted to check out how it looks before adding the rest, but I can't see it on the deploy preview: https://deploy-preview-67--trusting-lumiere-9c7fad.netlify.app/docs

anything I'm missing?

2021-06-15 15:32 UTC, lstkz commented
@TkDodo 
https://github.com/remeda/remeda/blob/master/scripts/generate.ts#L47
This line must be fixed to allow multiple exports from a single file.

2021-06-15 15:36 UTC, TkDodo commented
@lstkz should I rather create separate files for each guard? Would that be better for treeshaking, too?

2021-06-15 15:42 UTC, lstkz commented
@TkDodo Either approach is fine. Guards are very simple 1-liners. I am ok to have a single file but you can split them if you want.

2021-06-16 14:32 UTC, TkDodo commented
@lstkz I think I addressed everything, I hope I didn't make any copy-paste errors when doing the documentation 😅

2021-06-16 14:36 UTC, TkDodo commented on src/_reduceLazy.ts
> +interface LazyEmpty {
removed the generic because it's unused and it error'd when I imported `flatMap` in the docs building 😮

2021-06-16 14:36 UTC, TkDodo commented on src/guards.ts
> +export function isNot<T>(predicate: (data: T) => any): (data: T) => boolean;
not sure why we'd need this extra overload. The tests pass without it - should I remove it?

2021-06-16 14:36 UTC, TkDodo commented on src/identity.ts
>  export function identity<T>(value: T) {
documented this as well because it's exported but doesn't show up in the docs :)

2021-07-15 08:42 UTC, TkDodo commented
@lstkz what do you think please, is this ready to be merged?

2021-07-21 13:04 UTC, TkDodo commented
@lstkz if you are happy with this PR, I would merge it and make a new release somewhen this week 🚀

2021-07-21 13:09 UTC, lstkz approved these changes
Awesome job!

2021-07-21 13:20 UTC, merged

2021-07-21 13:28 UTC, TkDodo commented
@lstkz sorry to bother you again, I tried to make a release with the steps you provided here: https://github.com/remeda/remeda/pull/129#issuecomment-860855040

but couldn't make it work. do I need to run this on my fork or checking out the remeda repo, and do I have sufficient rights to do so? Thanks!

2021-07-21 13:31 UTC, lstkz commented
@TkDodo 
What errors do you have? The origin of the Github repo is not important. Make sure to log in to npm using `npm login`.

2021-07-21 13:48 UTC, TkDodo commented
> Make sure to log in to npm using npm login.

🤦  thanks, I think I succeeded 🚀  release is here: https://github.com/remeda/remeda/releases/tag/v0.0.29

Thanks!