feat prop: Allow to use `prop` without specifying generic types
remeda/remeda pull request #920
Opened 2024-11-14 14:49 UTC by Masyaka

> Replace this quote with a description of your changes

---

Make sure that you:

- [*] Typedoc added for new methods and updated for changed
- [*] Tests added for new methods and updated for changed
- [*] New methods added to `src/index.ts`
- [*] New methods added to `docs/src/content/mapping` for both Lodash and Ramda.

---

<details><summary>We use semantic PR titles to automate the release process!</summary>

https://conventionalcommits.org

PRs should be titled following using the format: `< TYPE >(< scope >)?: description`

### Available Types:

- `feat`: new functions, and changes to a function's type that would impact users.
- `fix`: changes to the runtime behavior of an existing function, or refinements to it's type that shouldn't impact most users.
- `test`: tests-only changes (transparent to users of the function).
- `docs`: changes to the documentation of a function **or the documentation site**.
- `build`, `ci`, `chore`, and `revert`: are only relevant for the internals of the library.

For scope put the name of the function you are working on (either new or
existing).

</details>

2024-11-15 16:16 UTC, eranhirsch requested changes
We usually don't cater in the library to the use-cases where the function returned from our curried data-last variant is stored and then used as a stand-alone function, e.g.:

```ts
const foo = prop("a");
foo(DATA);
```

We don't consider passing in explicit type parameters as part of our API. That is, if a function doesn't work without any type parameters passed in, then it's either a type bug or not supported by the library.

BUT... in this case, it looks like this works fine and doesn't break anything, so I'm OK with adding this extra signature to the function. This also comes up a lot in issues, so many people would be happy with it. I ALSO managed to create a type test that shows that breaks without this change, which brings me to my main point:

Please add tests to your change. The tests should be built so that they would break before adding your change and would be green after adding it. Please add enough tests to show that this doesn't break any of the existing usages of the utility function. I'm aware that this function isn't tested well to begin with, so it would be really helpful if you could add enough tests to make our testing more robust for it.

2024-11-26 06:54 UTC, eranhirsch commented
@Masyaka , are you planning on continuing to work on this?

2024-11-26 07:00 UTC, Masyaka commented
> @Masyaka , are you planning on continuing to work on this?

Yes, will finish it at this week

2024-12-02 13:45 UTC, Masyaka commented
Why actually I decided to add those changes, there is the jsdoc with signature:
<img width="581" alt="image" src="https://github.com/user-attachments/assets/652fe032-387e-4bf0-95fd-50c293831b39">
This signature was not working, before this PR

2024-12-09 15:14 UTC, eranhirsch approved these changes
This is great, thanks for helping us out. I'm sure a lot of people would find this useful. Please check out my nits about the tests, and I will merge this once you send a fix.

2024-12-16 15:37 UTC, eranhirsch approved these changes

2024-12-16 15:37 UTC, eranhirsch commented on src/prop.test-d.ts
> +  expectTypeOf(valueB).toEqualTypeOf<unknown>();
```suggestion
```

2024-12-16 15:38 UTC, eranhirsch commented on src/prop.test-d.ts
> +  const valueB = standAlonePropB(item);
```suggestion
  // @ts-expect-error [ts2322] -- b is not a key of typeof item
  standAlonePropB({ a: 1 });
```

2024-12-16 15:54 UTC, merged

2024-12-16 15:56 UTC, TkDodo commented
:tada: This PR is included in version 2.17.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/remeda/v/2.17.5)
- [GitHub release](https://github.com/remeda/remeda/releases/tag/v2.17.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: